/* Gaurd */
#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

/* TIMER0 Configurations */

/* Choose TIMER0 Prescaller division factor
	Options: 1- NO_CLOCK
			 2-	DIVIDE_BY_1
			 3- DIVIDE_BY_8
			 4- DIVIDE_BY_64
			 5- DIVIDE_BY_256
			 6- DIVIDE_BY_1024
			 7- EXTERNAL_SRC_FALLING_EDGE
			 8- EXTERNAL_SRC_RISING_EDGE
*/
#define TIMER0_u8_PRESCALLER		DIVIDE_BY_8

/* Choose TIMER0 Mode
	Options: 1- TIMER0_OVERFLOW_MODE
			 2- TIMER0_CTC_MODE
			 3- TIMER0_FAST_PWM_MODE
			 4- TIMER0_PHASE_CORRECT_PWM_MODE
*/
#define TIMER0_u8_MODE				TIMER0_OVERFLOW_MODE

/* Choose the preload value */
#define TIMER0_u8_PRELOAD			0	

/* Choose TIMER0 Interrupt
	Options: 1- TIMER0_OVERFLOW_INTERRUPT_ENABLE
			 2- TIMER0_CTC_INTERRUPT_ENABLE
*/
#define TIMER0_u8_INTERRUPT			TIMER0_OVERFLOW_INTERRUPT_ENABLE

#define TIMER0_COMPARE_REGISTER_INITAL_VALUE	250

/* Choose TIMER0 Fast PWM Mode Type:
 * 	Options: 1- TIMER0_INVERTING
 * 			 2- TIMER0_NON_INVERTING
 */
#define TIMER0_INVERTING_TYPE	TIMER0_NON_INVERTING

#endif /* TIMER_CONFIG_H_ */
